name:                   Linters

on:                     pull_request

jobs:
  rubocop:
    name:               Rubocop
    runs-on:            ubuntu-latest
    steps:
      - uses:           actions/checkout@v2
      - uses:           actions/setup-ruby@v1
        with:
          ruby-version: ">=2.7.x"
      - name:           Setup Rubocop
        run:            |
          [ -f Gemfile ] && bundle update --bundler
          [ -f Gemfile ] && bundle add rubocop
          [ -f Gemfile ] && bundle install
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml
      - name:           Rubocop Report
        run:            bundle exec rubocop --color
